services:
  database:
    restart: on-failure
    image: mysql:latest
    container_name: database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: libreria
    networks:
      - ayd2

  backend:
    restart: on-failure
    build: ./Backend
    ports:
      - "5000:5000"
    container_name: backend
    env_file:
      - ./Backend/.env
    environment:
      MYSQL_HOST: database
    depends_on:
      - database
    networks:
      - ayd2

  frontend:
    restart: on-failure
    build: ./Frontend
    ports:
      - "3000:3000"
    container_name: frontend
    env_file:
      - ./Frontend/.env
    depends_on:
      - backend
      - database
    networks:
      - ayd2

networks:
  ayd2:
 
